#!/bin/csh
echo "Latexing #1..."
/usr/bin/latex final
if ($status != 0) exit 1

echo "Bibtexing..."
/usr/bin/bibtex final
echo "Bibtex status $status"
#if ($status != 0) exit 1

echo "Latexing #2..."
/usr/bin/latex final
if ($status != 0) exit 1

echo "Latexing #3..."
/usr/bin/latex final
if ($status != 0) exit 1

echo "making glossaries"
/usr/bin/makeindex -s final.ist -t final.glg -o final.gls final.glo
/usr/bin/makeindex -s final.ist -t final.nlg -o final.ntn final.not

echo "Latexing #4..."
/usr/bin/latex final
if ($status != 0) exit 1

echo "Latexing #5..."
/usr/bin/latex final
if ($status != 0) exit 1

echo "Dvipsing..."
/usr/bin/dvips -o final.ps final.dvi

set wc = `cat f_*.tex fx_*.tex | wc -w`

echo "Completed: Words = $wc "
