#!/bin/csh
echo "Latexing #1..."
/usr/bin/latex main
if ($status != 0) exit 1

echo "Bibtexing..."
/usr/bin/bibtex main
echo "Bibtex status $status"
#if ($status != 0) exit 1

echo "Latexing #2..."
/usr/bin/latex main
if ($status != 0) exit 1

echo "Latexing #3..."
/usr/bin/latex main
if ($status != 0) exit 1

echo "Dvipsing..."
/usr/bin/dvips -o thesis.ps main.dvi

echo "Done"
